<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>TOPMed OMICS Progress Report</title>
    
    <!-- Bootstrap CSS -->
    <link href="../report/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="data:text/css;charset=utf-8," data-href="../report/dist/css/bootstrap-theme.min.css" rel="stylesheet" id="bs-theme-stylesheet">
    <link href="../report/css/docs.css" rel="stylesheet">
    <link href="../report/css/template.css" rel="stylesheet">
    <!-- jquery ui js and css for autocomplete -->
    <script src="https://code.jquery.com/jquery-3.7.1.js" integrity="sha256-eKhayi8LEQwp4NKxN+CfCh+3qOVUtJn3QNZ0TciWLP4=" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/ui/1.14.1/jquery-ui.js" integrity="sha256-9zljDKpE/mQxmaR4V2cGVaQ7arF3CcXxarvgr7Sj8Uc=" crossorigin="anonymous"></script>
    <link href="//code.jquery.com/ui/1.14.1/themes/base/jquery-ui.css" rel="stylesheet"/>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  </head>
  <body>
    <style>
      .bs-docs-header { background-image: linear-gradient(to bottom, #0f463c 0, #185f65 100%); }
      .bs-docs-header h1 { margin-right: auto }
      .bs-docs-footer { height: 30px; margin: 20px 0; padding: 40px 0; background-color: #0f463c; color: #fff;}
      .chartheader { text-align: center; color: #1b809e }
      .bs-callout-info h3 { font-weight: normal }
      .bs-docs-nav .navbar-brand, .bs-docs-nav .navbar-nav>li>a
      { background: white; } 
    </style>
    <header class="navbar navbar-static-top bs-docs-nav" id="top" role="banner">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">TOPMed IRC</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li><a href ="index.php">OMICS</a></li>  
            <li class="active"><a href="#">About</a></li>   
            <li><a href="../report/">Whole genomes</a></li>
          </ul>
        </div>
      </div>
    </header>

    <div class="bs-docs-header" id="content" tabindex="-1">
      <div class="container">
        <h1 id="subject">TOPMed OMICS Progress Report</h1>
        <h4><strong>Last updated</strong> : <?=date("m/d/Y");?></h4>
         <p class="lead">This page reports TOPMed Omics data received by the IRC.
        </p>
      </div>
    </div>

    <div class="container bs-docs-container">
      <div class="bs-callout bs-callout-info">
        <h3 id="about">About</h3>
      </div>
      <p>The NIH National Heart, Lung and Blood Institute (NHLBI) TOPMed program is generating three types of omics data:  RNA sequencing, DNA methylation and metabolomics for selected participants from ongoing NHLBI-funded research studies. The TOPMed Informatics Research Center (IRC) at the University of Michigan coordinates omics bulk data receipt, storage, distribution and deposit to dbGaP, in collaboration with the TOPMed Data Coordinating Center (DCC) at the University of Washington.  The DCC collects, processes and submits to dbGaP the sample metadata and omics data summary files.<p>
      <p>The goal of this web site is to provide a current view of data received by the IRC and access to RNA-seq quality control measures generated by the omics centers.</P>
      <p>&nbsp;</p>
      <div class="bs-callout bs-callout-info">
        <h3 id="contact">Contact</h3>
      </div>
      <p>For general questions regarding the TOPMed WGS project, please contact the IRC (topmed.informatics@umich.edu). For questions regarding the website and its content, please contact Kevin Li (kevinwli@umich.edu).
      </p>
      <p>&nbsp;</p>
      <div class="bs-callout bs-callout-info">
        <h3 id="credit">Courtesy</h3>
      </div>
      <p>In this OMICS progress report, we use the following Javascript charting tools: 
      </p>
      <p>
        <a href="https://www.highcharts.com/" target="_BLANK">HighCharts</a>: A modern SVG-based, multi-platform charting library.  
      </p>
      <p>
        <a href="http://tabulator.info" target="_BLANK">Tabulator</a>: The easy to use, fully featured, interactive table JavaScript library.
      </p>
    </div>
    <footer class="bs-docs-footer">
      <div class="container">
        <p>&copy; <?=date("Y"); ?> All Rights Reserved </p>
      </div>
    </footer>
  </body>
</html>

